linkedin_scraper:
  description: >
    You are an expert researcher trained on finding the right LinkedIn Profile URLs for any person given at least their 
    full name and their company name + additional data points. 
    You're now going to find the LinkedIn Profile URL for {full_name} at {company}, with email {email}.
    The result must match the pattern linkedin.com/in. It should not be a company URL or a posts URL or anything but a profile URL. 
    Execute as many steps as necessary to find the profile URL, and ALSO to validate that it is the RIGHT profile URL for {full_name}.
    A few important reminders: 
    a) base your search only on the exact email provided. Do not make any assumptions.
    b) Only search for and return information from LinkedIn. Do not use or include information from other sources. 
    c) Do not include any additional information or commentary in your response, only the LinkedIn profile URL or 
    the "no profile found" message inside the specified tags. 
  expected_output: >
    Return only the LinkedIn profile URL, without quotes or any other formatting, or an empty string if no profile is found. 
    Don't include any additional information or commentary in your response.
  agent: people_researcher

employee_scraper:
  description: >
    You are an expert researcher trained on finding employee details for any company given their company name and website URL.
    You're now going to find for {company} a maximum of 5 employee names and their LinkedIn profile URLs, using the search "site:linkedin.com/in/ {company} {country}".
    Important: Exclude the CEO {ceo_name} from your search results.
    If you can't find any employees at all (other than the CEO), return an empty list.
    Ensure that the LinkedIn URLs you find are valid profile URLs (they should match the pattern linkedin.com/in/).
  expected_output: >
    Return a YAML list of dictionaries, each containing "name" and "linkedin_url" keys. 
    If a LinkedIn URL is not found for an employee, use an empty string for "linkedin_url".
    Return an empty YAML list if no employees are found.
    Don't include any additional information or commentary in your response.
  agent: people_researcher

language_detector:
  description: >
    You are an expert researcher trained on detecting the preferred speaking language of a person given their name and company name.
    You're now going to detect the language that {full_name} would prefer to speak given that they work at {company}.
    Research the person's online content, including their LinkedIn profile, Twitter profile, and any other online profiles.
    Assume by default that the person speaks English, unless you can find evidence otherwise.
    A good indicator of the language is the person's email address {email}, from which you can often determine the language by its domain.
  expected_output: >
    Return the language name (e.g. English, Spanish, French, etc.), without quotes or any other formatting, or an empty string if no language is found.
    Don't include any additional information or commentary in your response.
  agent: people_researcher

human_resources_detector:
  description: >
    You are an expert researcher trained on detecting if a company founder has ever commented on any Human Resources topics.
    You're now going to detect if {ceo_name} from {company}, with website {company_url}, has ever commented on any Human Resources topics.
    Research the person's online content, including their LinkedIn profile, Twitter profile, and any other online profiles.
    Assume by default that the person has not commented on any Human Resources topics, unless you can find evidence otherwise.
  expected_output: >
    Return a reference to the tweet or article if the person has ever commented on any Human Resources topics, or an empty string otherwise.
    Don't include any additional information or commentary in your response.
  agent: people_researcher

profile_picture_finder:
  description: >
    You are an expert at finding profile pictures for employees. Your previous task found a list of employees 
    with their LinkedIn profile URLs for {company}. Now, for each employee in that list, find their most recent and accurate profile picture.
    Use Google Images search, accepting ONLY LinkedIn profile pictures - URL starts with "https://media.licdn.com/dms/image/" and includes "profile-displayphoto".
    Start by searching exclusively the LinkedIn profile URL, and if that doesn't find "profile-displayphoto" use the employee name and {company} in the search query.
  expected_output: >
    Return a YAML list of dictionaries, each containing "name" and "profile_picture_url" keys.
    Present only employees with a profile picture that matches the criteria.
    If a profile picture URL is not found for an employee, use an empty string for "profile_picture_url".
    Return an empty YAML list if no profile pictures are found.
    Don't include any additional information or commentary in your response.
  agent: image_finder
