linkedin_scraper:
  description: >
    You are an expert researcher trained on finding the right LinkedIn Profile URLs for any person given at least their 
    full name and their company name + additional data points. 
    You're now going to find the LinkedIn Profile URL for {full_name} at {company}, with email {email}.
    The result must match the pattern linkedin.com/in. It should not be a company URL or a posts URL or anything but a profile URL. 
    Execute as many steps as necessary to find the profile URL, and ALSO to validate that it is the RIGHT profile URL for {full_name}.
    A few important reminders: 
    a) base your search only on the exact email provided. Do not make any assumptions.
    b) Only search for and return information from LinkedIn. Do not use or include information from other sources. 
    c) Do not include any additional information or commentary in your response, only the LinkedIn profile URL or 
    the "no profile found" message inside the specified tags. 
  expected_output: >
    Return only the LinkedIn profile URL, without quotes or any other formatting, or an empty string if no profile is found. 
    Don't include any additional information or commentary in your response.
  agent: researcher

employee_scraper:
  description: >
    You are an expert researcher trained on finding employee details for any company given their company name and website URL.
    You're now going to find for {company} 2 employee names, their job titles, and ideally their LinkedIn profile URLs.
    Use the company's official website {company_url} to search for an "about us", "team", or "about the company" page (if they exist).
    If you don't find employees there, try to search for specific titles such as "coo", "cto", "vp", "director", "manager", or similar.
    Important: Exclude the CEO {ceo_name} from your search results.
    Also important: there might be several versions of {company}, so use the exact URL {company_url} to find the correct one.
    If you can't find any employees at all (other than the CEO), return an empty list.
  expected_output: >
    Return the list of employee names, separated by commas, without quotes or any other formatting, or an empty string if no employees are found.
    Don't include any additional information or commentary in your response.
  agent: researcher

language_detector:
  description: >
    You are an expert researcher trained on detecting the preferred speaking language of a person given their name and company name.
    You're now going to detect the language that {full_name} would prefer to speak given that they work at {company}.
    Research the person's online content, including their LinkedIn profile, Twitter profile, and any other online profiles.
    Assume by default that the person speaks English, unless you can find evidence otherwise.
    A good indicator of the language is the person's email address {email}, from which you can often determine the language by its domain.
  expected_output: >
    Return the language name (e.g. English, Spanish, French, etc.), without quotes or any other formatting, or an empty string if no language is found.
    Don't include any additional information or commentary in your response.
  agent: researcher